on:
  push:
    tags:
      - '[0-9]+'

jobs:
  create-release:
    name: Create release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true
  releases-matrix:
    name: Release Go binaries
    needs: create-release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm, arm64]
        exclude:
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: darwin
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Get go version
        id: get_go_version
        run: sed -n -E '/^FROM/ {s/^FROM golang:([0-9.]+).*/go_version=\1/p;q}' test.txt >> $GITHUB_OUTPUT
      - uses: wangyoucao577/go-release-action@v1.37
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            goversion: ${{ steps.get_go_version.outputs.go_version }}
            goos: ${{ matrix.goos }}
            goarch: ${{ matrix.goarch }}
            release_tag: ${{ steps.get_version.outputs.version }}
            ldflags: -X main.version=${{ steps.get_version.outputs.version }}
